In [1]:
import numpy as np
array_of_ones = np.ones((3,4))

array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
# How to specify datatype?
# By using dtype function

array_of_ones_int = np.ones((3,4), dtype = np.int16)

array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [6]:
array_empty = np.empty((2,3))

array_empty

array([[4.63905145e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [8]:
# Creating an identity matrix

# np.eye()

array_eye = np.eye(4)

array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
# range in python -- arange in numpy
# syntax - arange(start, stop, step)  -- it also accepts float arguments

# Print even numbers till 20

array_of_evens = np.arange(2, 20, 2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
array_of_float = np.arange(1,2,0.3)
array_of_float

array([1. , 1.3, 1.6, 1.9])

In [15]:
# Introduction to 2 dimensional arrays

array_2d = np.array([(2,4,6),(3,5,7)])
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [16]:
# how to verify?

array_2d.shape

(2, 3)

In [17]:
array_of_float.shape

(4,)

In [18]:
array_of_evens.shape

(9,)

In [19]:
# How to create n dimensional arrays?
# By using .reshape()

In [20]:
array_nd = np.arange(6).reshape(3,2)

array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
array_nd.shape

(3, 2)