In [1]:
#Indexing & Slicing
import numpy as np
a = np.arange(11)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [2]:
a[2]

4

In [3]:
a[-4]

49

In [4]:
a[2,4]

IndexError: too many indices for array

In [5]:
a[2:4]

array([4, 9])

In [6]:
a[2:-2] # Starting inclusive, ending value exclusive

array([ 4,  9, 16, 25, 36, 49, 64])

In [7]:
# www.hackerrank.com -- Sign up and practice Python

In [8]:
a[2:]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
a[:5]

array([ 0,  1,  4,  9, 16])

In [10]:
a[:11:2] # [start:stop:step]

array([  0,   4,  16,  36,  64, 100])

In [11]:
a[-1:-4]

array([], dtype=int64)

In [13]:
 # How to print array of numbers in a reverse order by using -ve indexing?
a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])

In [14]:
a[:-1]

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
a[a]