In [1]:
#Introduction to Numpy

#Creating arrays
#
#
#What exactly Numpy is -- Numpy is a numerical computing package.
# Python cannot support the functionality what numpy provides directly.

#We basically deal with multi-dimentional data -- ndarray
#core scientific package -- supports wide variety of operations
#Operations ML computations such as linear algebra, random number capabilities
#Basic building block oh numpy is a powerful n-dimentional array
# It forms the core of the python eco system -- all the external libraries comes under the eco system of python
#python eco system of open source for amth, science and engineering, numpy forms the core of these things!
#

#Numpy demo -1
#Check whether numpy is installed? By default jupyter gets this installed

!pip install numpy

In [2]:
!pip install numpy --upgrade

    100% |████████████████████████████████| 20.3MB 1.8MB/s eta 0:00:01
tables 3.5.1 requires mock>=2.0, which is not installed.
  Found existing installation: numpy 1.16.2
    Uninstalling numpy-1.16.2:
      Successfully uninstalled numpy-1.16.2


In [3]:
!pip install numpy

In [4]:
# Creating numpy sample arrays

import numpy as np       # kind of alias name

array_one = np.array([1, 2, 3, 4])

array_one

array([1, 2, 3, 4])

In [5]:
numbers = [9,8,7,6]

array_two = np.array(numbers)

array_two

array([9, 8, 7, 6])

In [12]:
# *** array of zeros

array_of_zeros = np.zeros((3,4))  # 3 rows & 4 columns

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# ***array of ones

array_of_ones = np.ones((5,5))  # 5 rows & 5 columns

array_of_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])